stages:
  load_data:
    cmd: python src/load_data.py --config=params.yaml
    deps:
    - src/get_data.py
    - src/load_data.py
    - data_given/diabetes.csv 
    outs:
    - data/raw/diabetes.csv

  split_data: 
    cmd: python src/split_data.py --config=params.yaml
    deps:
    - src/split_data.py
    - data/raw/diabetes.csv
    outs:
    - data/processed/train_diabetes.csv
    - data/processed/test_diabetes.csv  

  train_and_evaluate:
    cmd: python src/train_and_evaluate.py --config=params.yaml
    deps:
    - data/processed/train_diabetes.csv
    - data/processed/test_diabetes.csv
    - src/train_and_evaluate.py
    params:
    - estimators.ElasticNet.params.alpha
    - estimators.ElasticNet.params.l1_ratio
    metrics:
    - reports/scores.json:
        cache: False
    - reports/params.json:
        cache: False
    outs: 
      - saved_models/model.joblib                
