stages:
  load_data:
    cmd: python src/load_data.py --config=params.yaml
    deps:
    - src/get_data.py
    - src/load_data.py
    - data_given/diabetes.csv 
    outs:
    - data/raw/diabetes.csv

  process_data: 
    cmd: python src/preprocess_data.py --config=params.yaml
    deps:
    - src/preprocess_data.py
    - data/raw/diabetes.csv
    outs:
    - data/processed/x_train.csv
    - data/processed/x_test.csv
    - data/processed/y_train.csv
    - data/processed/y_test.csv  

  train_and_evaluate:
    cmd: python src/train_and_evaluate.py --config=params.yaml
    deps:
    - data/processed/x_train.csv
    - data/processed/x_test.csv
    - data/processed/y_train.csv
    - data/processed/y_test.csv 
    - src/train_and_evaluate.py
    params:
    - estimators.Logistic.params.solver
    - estimators.Logistic.params.verbose
    metrics:
    - reports/scores.json:
        cache: False
    - reports/params.json:
        cache: False
    outs: 
      - saved_models/model.joblib                
